on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run:  |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Failed"}' ${{ secrets.DEVOPS_SLACK_URL }}
